inputs:
  - name: None
    input_class: AuxInput
    address: off
    group: 1
  - name: Spotify
    input_class: SpotifyInput
    icon: spotify.png
    group: 2
  - name: StuBru
    input_class: StreamInput
    url: http://icecast-servers.vrtcdn.be/stubru-high.mp3
    icon: stubru.png
    group: 3
  - name: Radio 1
    input_class: StreamInput
    url: http://icecast-servers.vrtcdn.be/radio1-high.mp3
    icon: radio1.png
    group: 3
  - name: Klara
    input_class: StreamInput
    url: http://icecast-servers.vrtcdn.be/klara-high.mp3
    icon: klara.png
    group: 3
  - name: Bluetooth
    input_class: AuxInput
    address: 2
    icon: bluetooth.png
    group: 2

zones:  # address: name
  0: Eetkamer
  1: Badkamer
  2: Terras

input_address_rpi : 1

logging:
  log_level: DEBUG
  log_file: /var/log/audio_controller/ac_log_{now}.txt

emulated: False